#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/openwrt-bulder.yml
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: 删除 workflow runs

on:
  repository_dispatch:
  workflow_dispatch:


env:
  TZ: Asia/Shanghai

jobs:

  build:
    runs-on: ubuntu-20.04
    name: 删除 workflow runs
    steps:
    - name: 签入项目
      uses: actions/checkout@main

    - name: 删除 workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 2

